apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: salquier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: "csi-cinder-high-speed"